name: Deploy to Server
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install
      - run: num test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
#      - name: Check out Repo
#        uses: action/checkout@v3
      - name: Deploy to the serve
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 54.236.79.196
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/ed.thebyrnefamily.ca
            git pull
              
